### ISSUE TITLE
automatically wraps the line don't work

### ISSUE THREAD

**Issue by mrtpcet** [standardnotes/markdown-visual#3]
https://user-images.githubusercontent.com/60814449/157901761-545c4c4e-d122-480b-a305-70e64deaea48.mp4

Sorry for my english

**Comment by mrtpcet** [comment]
I still have the issue on macOS Catalina and Standardnotes v3.13 
![image](https://user-images.githubusercontent.com/60814449/159732742-22b7b9b7-d04a-478a-aecc-800f27b39496.png)

**Comment by atmoio** [comment]
So while it's fixed in here, it still requires deployment in our apps :) So this will be included in the next app update.

**Comment by mrtpcet** [comment]
Ok thanks !

**Comment by mrtpcet** [comment]
I still have the issue on iOS app
![IMG_92D38C463D63-1](https://user-images.githubusercontent.com/60814449/161969763-3b64742e-0642-4a4a-a1a5-47521b77a979.jpeg)
